language = "Python"

[redpanda_config]
broker = "localhost:19092"
message_timeout_ms = 1000
retention_ms = 30000
replication_factor = 1

[clickhouse_config]
db_name = "dbo"
user = { from_env = "MOOSE_CLICKHOUSE_USER" }
password = { from_env = "MOOSE_CLICKHOUSE_PASSWORD" }
use_ssl = { from_env = "MOOSE_CLICKHOUSE_USE_SSL", default = true }
host = { from_env = "MOOSE_CLICKHOUSE_HOST" }
host_port = { from_env = "MOOSE_CLICKHOUSE_HOST_PORT", default = 8443 }
native_port = { from_env = "MOOSE_CLICKHOUSE_NATIVE_PORT", default = 8443 }

[http_server_config]
host = "localhost"
port = 4200
management_port = 5001
proxy_port = 4201

[redis_config]
url = "redis://127.0.0.1:6379"
key_prefix = "MS"

[git_config]
main_branch_name = "main"

[temporal_config]
db_user = "temporal"
db_password = "temporal"
db_port = 5432
temporal_host = "localhost"
temporal_port = 7233
temporal_version = "1.22.3"
admin_tools_version = "1.22.3"
ui_version = "2.21.3"
ui_port = 8080
ui_cors_origins = "http://localhost:3008"
config_path = "config/dynamicconfig/development-sql.yaml"
postgresql_version = "13"
client_cert = ""
client_key = ""
ca_cert = ""
api_key = ""

[supported_old_versions]

[authentication]

[s3_config]
# S3/MinIO configuration for unstructured data storage
endpoint_url = ""  # MinIO endpoint, set to empty string for AWS S3
access_key_id = { from_env = "MOOSE_S3_ACCESS_KEY_ID" }
secret_access_key = { from_env = "MOOSE_S3_SECRET_ACCESS_KEY" }
region_name = { from_env = "MOOSE_S3_REGION_NAME", default = "us-east-2" }
bucket_name = { from_env = "MOOSE_S3_BUCKET_NAME", default = "yl-billing-data" }
signature_version = "s3v4"

[features]
streaming_engine = true
workflows = true
data_model_v2 = true
