#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_DIR="$(dirname "$SCRIPT_DIR")"
TEMPLATE_FILE="$SERVICE_DIR/moose.config.template.toml"
OUTPUT_FILE="$SERVICE_DIR/moose.config.toml"
ENV_FILE="$SERVICE_DIR/.env"

if [[ ! -f "$TEMPLATE_FILE" ]]; then
    echo "[render-config] Template not found: $TEMPLATE_FILE" >&2
    exit 1
fi

ensure_envsubst() {
    if command -v envsubst >/dev/null 2>&1; then
        return
    fi

    if command -v apt-get >/dev/null 2>&1; then
        echo "[render-config] 'envsubst' not found. Attempting to install via 'sudo apt-get install -y gettext-base'..."
        if sudo apt-get install -y gettext-base >/dev/null; then
            return
        fi
        echo "[render-config] Automatic installation failed. Please install gettext-base manually." >&2
    else
        echo "[render-config] 'envsubst' is required but not found. Install gettext-base (GNU gettext) and retry." >&2
    fi

    exit 1
}

ensure_envsubst

if [[ -f "$ENV_FILE" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
fi

# Default values - External services by default
: "${MOOSE_CLICKHOUSE_DB_NAME:=finops-odw}"
: "${MOOSE_CLICKHOUSE_USER:=finops}"
: "${MOOSE_CLICKHOUSE_PASSWORD:=cU2f947&9T{6d}"
: "${MOOSE_CLICKHOUSE_USE_SSL:=true}"
: "${MOOSE_CLICKHOUSE_HOST:=ck.mightytech.cn}"
: "${MOOSE_CLICKHOUSE_HOST_PORT:=8443}"
: "${MOOSE_CLICKHOUSE_NATIVE_PORT:=9000}"

: "${MOOSE_TEMPORAL_DB_USER:=temporal}"
: "${MOOSE_TEMPORAL_DB_PASSWORD:=temporal}"
: "${MOOSE_TEMPORAL_DB_PORT:=5432}"
: "${MOOSE_TEMPORAL_HOST:=localhost}"
: "${MOOSE_TEMPORAL_PORT:=7233}"

: "${TEMPORAL_DB_HOST:=marspbi.postgres.database.chinacloudapi.cn}"
: "${TEMPORAL_DB_PORT:=5432}"
: "${TEMPORAL_HOST:=temporal}"
: "${TEMPORAL_PORT:=7233}"

: "${MOOSE_S3_ENDPOINT_URL:=}"
: "${MOOSE_S3_ACCESS_KEY_ID:=}"
: "${MOOSE_S3_SECRET_ACCESS_KEY:=}"
: "${MOOSE_S3_REGION_NAME:=us-east-2}"
: "${MOOSE_S3_BUCKET_NAME:=yl-billing-data}"
: "${MOOSE_S3_SIGNATURE_VERSION:=s3v4}"

# Normalise boolean/string casing
MOOSE_CLICKHOUSE_USE_SSL=$(echo "$MOOSE_CLICKHOUSE_USE_SSL" | tr '[:upper:]' '[:lower:]')

VARS=(
    MOOSE_CLICKHOUSE_DB_NAME
    MOOSE_CLICKHOUSE_USER
    MOOSE_CLICKHOUSE_PASSWORD
    MOOSE_CLICKHOUSE_USE_SSL
    MOOSE_CLICKHOUSE_HOST
    MOOSE_CLICKHOUSE_HOST_PORT
    MOOSE_CLICKHOUSE_NATIVE_PORT
    MOOSE_TEMPORAL_DB_USER
    MOOSE_TEMPORAL_DB_PASSWORD
    MOOSE_TEMPORAL_DB_PORT
    MOOSE_TEMPORAL_HOST
    MOOSE_TEMPORAL_PORT
    TEMPORAL_DB_HOST
    TEMPORAL_DB_PORT
    TEMPORAL_HOST
    TEMPORAL_PORT
    MOOSE_S3_ENDPOINT_URL
    MOOSE_S3_ACCESS_KEY_ID
    MOOSE_S3_SECRET_ACCESS_KEY
    MOOSE_S3_REGION_NAME
    MOOSE_S3_BUCKET_NAME
    MOOSE_S3_SIGNATURE_VERSION
)

export "${VARS[@]}"

# Generate moose.config.toml
TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT

PATTERN="$(printf ' ${%s}' "${VARS[@]}")"
envsubst "$PATTERN" < "$TEMPLATE_FILE" > "$TMP_FILE"

if [[ ! -f "$OUTPUT_FILE" ]] || ! cmp -s "$TMP_FILE" "$OUTPUT_FILE"; then
    mv "$TMP_FILE" "$OUTPUT_FILE"
else
    rm -f "$TMP_FILE"
fi

echo "[render-config] Generated $OUTPUT_FILE from template"

# Generate Docker Compose override file
OVERRIDE_FILE="$SERVICE_DIR/.moose/docker-compose.override.yml"
generate_docker_override() {
    # Ensure .moose directory exists
    mkdir -p "$(dirname "$OVERRIDE_FILE")"
    local clickhouse_external=false
    local temporal_db_external=false
    
    # Check if ClickHouse is external
    case "$MOOSE_CLICKHOUSE_HOST" in
        localhost|127.*|clickhousedb)
            clickhouse_external=false
            ;;
        *)
            clickhouse_external=true
            ;;
    esac
    
    # Check if Temporal DB is external
    case "$TEMPORAL_DB_HOST" in
        localhost|127.*|postgresql|temporal-postgresql)
            temporal_db_external=false
            ;;
        *)
            temporal_db_external=true
            ;;
    esac
    
    cat > "$OVERRIDE_FILE" << 'EOF'
# Auto-generated by scripts/render-config.sh to control optional infrastructure services.
services:
EOF

    if [[ "$clickhouse_external" == true ]]; then
        cat >> "$OVERRIDE_FILE" << 'EOF'
  # ClickHouse services disabled - using external ClickHouse
  clickhousedb:
    deploy:
      replicas: 0
    scale: 0
    profiles:
      - disabled-never-start
    ports: []  # Remove all port mappings
  clickhouse-keeper:
    deploy:
      replicas: 0
    scale: 0
    profiles:
      - disabled-never-start
    ports: []  # Remove all port mappings
EOF
    else
        cat >> "$OVERRIDE_FILE" << 'EOF'
  # ClickHouse services enabled for local development
  clickhousedb:
    profiles:
      - clickhouse
  clickhouse-keeper:
    profiles:
      - clickhouse
EOF
    fi

    if [[ "$temporal_db_external" == true ]]; then
        cat >> "$OVERRIDE_FILE" << 'EOF'
  # Disable local PostgreSQL since using external database
  postgresql:
    profiles:
      - disabled
  temporal:
    profiles:
      - temporal
    depends_on: []  # No local dependencies since using external PostgreSQL
    environment:
      - DB=postgres12
      - DB_PORT=${TEMPORAL_DB_PORT:-5432}
      - POSTGRES_USER=${TEMPORAL_DB_USER:-temporal}
      - POSTGRES_PWD=${TEMPORAL_DB_PASSWORD:-temporal}
      - POSTGRES_SEEDS=${TEMPORAL_DB_HOST:-postgresql}
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamicconfig/development-sql.yaml
    restart: on-failure
  temporal-admin-tools:
    profiles:
      - temporal
    depends_on:
      temporal:
        condition: service_healthy
    environment:
      - TEMPORAL_ADDRESS=${MOOSE_TEMPORAL_HOST:-temporal}:${MOOSE_TEMPORAL_PORT:-17233}
      - TEMPORAL_CLI_ADDRESS=${MOOSE_TEMPORAL_HOST:-temporal}:${MOOSE_TEMPORAL_PORT:-17233}
  temporal-ui:
    profiles:
      - temporal
    depends_on:
      temporal:
        condition: service_healthy
    environment:
      - TEMPORAL_ADDRESS=${MOOSE_TEMPORAL_HOST:-temporal}:${MOOSE_TEMPORAL_PORT:-17233}
EOF
    else
        cat >> "$OVERRIDE_FILE" << 'EOF'
  # Local PostgreSQL and Temporal services enabled
  postgresql:
    profiles:
      - temporal-db
  temporal:
    profiles:
      - temporal
  temporal-admin-tools:
    profiles:
      - temporal
  temporal-ui:
    profiles:
      - temporal
EOF
    fi

    echo "[render-config] Generated Docker Compose override: $OVERRIDE_FILE"
    echo "[render-config] ClickHouse external: $clickhouse_external (host: $MOOSE_CLICKHOUSE_HOST)"
    echo "[render-config] Temporal DB external: $temporal_db_external (host: $TEMPORAL_DB_HOST)"
}

generate_docker_override
