/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type Bar = {
    /**
     * @type string, uuid
    */
    id: string;
    /**
     * @type string, uuid
    */
    foo_id: string;
    /**
     * @type integer
    */
    value: number;
    /**
     * @type string | undefined
    */
    label?: string;
    /**
     * @type string | undefined
    */
    notes?: string;
    /**
     * @type boolean
    */
    is_enabled: boolean;
    /**
     * @type string, date-time
    */
    created_at: string;
    /**
     * @type string, date-time
    */
    updated_at: string;
    /**
     * @type string, date-time
    */
    _peerdb_synced_at: string;
    /**
     * @type integer
    */
    _peerdb_is_deleted: number;
    /**
     * @type integer
    */
    _peerdb_version: number;
};