/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type Foo = {
    /**
     * @type string, uuid
    */
    id: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @type string
    */
    status: string;
    /**
     * @type integer
    */
    priority: number;
    /**
     * @type boolean
    */
    is_active: boolean;
    /**
     * @type string | undefined
    */
    metadata?: string;
    /**
     * @type array
    */
    tags: string[];
    /**
     * @pattern ^-?\d+(\.\d+)?$
     * @type string | undefined
    */
    score?: string;
    /**
     * @type string | undefined
    */
    large_text?: string;
    /**
     * @type string, date-time
    */
    created_at: string;
    /**
     * @type string, date-time
    */
    updated_at: string;
    /**
     * @type string, date-time
    */
    _peerdb_synced_at: string;
    /**
     * @type integer
    */
    _peerdb_is_deleted: number;
    /**
     * @type integer
    */
    _peerdb_version: number;
};