/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type FooCubeAggregationRow = {
    month: (null | string);
    status: (null | string);
    tag: (null | string);
    priority: (null | number);
    /**
     * @type number
    */
    n: number;
    /**
     * @type number
    */
    avgScore: number;
    /**
     * @type number
    */
    p50: number;
    /**
     * @type number
    */
    p90: number;
};