/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type FoosScoreOverTimeDataPoint = {
    /**
     * @type string
    */
    date: string;
    /**
     * @type number
    */
    averageScore: number;
    /**
     * @type number
    */
    totalCount: number;
};