/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetBarsAverageValueResponse } from "./GetBarsAverageValueResponse.ts";

/**
 * @description Successful operation
*/
export type GetApiBarAverageValue200 = GetBarsAverageValueResponse;

export type GetApiBarAverageValueQueryResponse = GetApiBarAverageValue200;

export type GetApiBarAverageValueQuery = {
    Response: GetApiBarAverageValue200;
    Errors: any;
};