/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetFoosResponse } from "./GetFoosResponse.ts";

export type GetApiFooQueryParams = {
    /**
     * @type number | undefined
    */
    limit?: number;
    /**
     * @type number | undefined
    */
    offset?: number;
    /**
     * @type string | undefined
    */
    sortBy?: string;
    /**
     * @type string | undefined
    */
    sortOrder?: string;
};

/**
 * @description Successful operation
*/
export type GetApiFoo200 = GetFoosResponse;

export type GetApiFooQueryResponse = GetApiFoo200;

export type GetApiFooQuery = {
    Response: GetApiFoo200;
    QueryParams: GetApiFooQueryParams;
    Errors: any;
};