/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetFooCubeAggregationsResponse } from "./GetFooCubeAggregationsResponse.ts";

export type GetApiFooCubeAggregationsQueryParams = {
    /**
     * @type number | undefined
    */
    months?: number;
    /**
     * @type string | undefined
    */
    status?: string;
    /**
     * @type string | undefined
    */
    tag?: string;
    /**
     * @type number | undefined
    */
    priority?: number;
    /**
     * @type number | undefined
    */
    limit?: number;
    /**
     * @type number | undefined
    */
    offset?: number;
    /**
     * @type string | undefined
    */
    sortBy?: string;
    /**
     * @type string | undefined
    */
    sortOrder?: string;
};

/**
 * @description Successful operation
*/
export type GetApiFooCubeAggregations200 = GetFooCubeAggregationsResponse;

export type GetApiFooCubeAggregationsQueryResponse = GetApiFooCubeAggregations200;

export type GetApiFooCubeAggregationsQuery = {
    Response: GetApiFooCubeAggregations200;
    QueryParams: GetApiFooCubeAggregationsQueryParams;
    Errors: any;
};