/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetBarsResponse } from "./GetBarsResponse.ts";

export type GetApiBarQueryParams = {
    /**
     * @type number | undefined
    */
    limit?: number;
    /**
     * @type number | undefined
    */
    offset?: number;
    /**
     * @type string | undefined
    */
    sortBy?: string;
    /**
     * @type string | undefined
    */
    sortOrder?: string;
};

/**
 * @description Successful operation
*/
export type GetApiBar200 = GetBarsResponse;

export type GetApiBarQueryResponse = GetApiBar200;

export type GetApiBarQuery = {
    Response: GetApiBar200;
    QueryParams: GetApiBarQueryParams;
    Errors: any;
};