/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetFoosScoreOverTimeResponse } from "./GetFoosScoreOverTimeResponse.ts";

export type GetApiFooScoreOverTimeQueryParams = {
    /**
     * @type number | undefined
    */
    days?: number;
};

/**
 * @description Successful operation
*/
export type GetApiFooScoreOverTime200 = GetFoosScoreOverTimeResponse;

export type GetApiFooScoreOverTimeQueryResponse = GetApiFooScoreOverTime200;

export type GetApiFooScoreOverTimeQuery = {
    Response: GetApiFooScoreOverTime200;
    QueryParams: GetApiFooScoreOverTimeQueryParams;
    Errors: any;
};