/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetFoosAverageScoreResponse } from "./GetFoosAverageScoreResponse.ts";

/**
 * @description Successful operation
*/
export type GetApiFooAverageScore200 = GetFoosAverageScoreResponse;

export type GetApiFooAverageScoreQueryResponse = GetApiFooAverageScore200;

export type GetApiFooAverageScoreQuery = {
    Response: GetApiFooAverageScore200;
    Errors: any;
};