/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetFooFiltersValuesResponse } from "./GetFooFiltersValuesResponse.ts";

export type GetApiFooFiltersValuesQueryParams = {
    /**
     * @type number | undefined
    */
    months?: number;
};

/**
 * @description Successful operation
*/
export type GetApiFooFiltersValues200 = GetFooFiltersValuesResponse;

export type GetApiFooFiltersValuesQueryResponse = GetApiFooFiltersValues200;

export type GetApiFooFiltersValuesQuery = {
    Response: GetApiFooFiltersValues200;
    QueryParams: GetApiFooFiltersValuesQueryParams;
    Errors: any;
};