/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetBarsAverageValueResponse = {
    /**
     * @type number
    */
    averageValue: number;
    /**
     * @type number
    */
    queryTime: number;
    /**
     * @type number
    */
    count: number;
};