/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetFoosAverageScoreResponse = {
    /**
     * @type number
    */
    averageScore: number;
    /**
     * @type number
    */
    count: number;
    /**
     * @type number
    */
    queryTime: number;
};