/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FoosScoreOverTimeDataPoint } from "./FoosScoreOverTimeDataPoint.ts";

export type GetFoosScoreOverTimeResponse = {
    /**
     * @type array
    */
    data: FoosScoreOverTimeDataPoint[];
    /**
     * @type number
    */
    queryTime: number;
};