/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Foo } from "./Foo.ts";

export type GetFoosResponse = {
    /**
     * @type array
    */
    data: Foo[];
    /**
     * @type object
    */
    pagination: {
        /**
         * @type number
        */
        limit: number;
        /**
         * @type number
        */
        offset: number;
        /**
         * @type number
        */
        total: number;
        /**
         * @type boolean
        */
        hasMore: boolean;
    };
    /**
     * @type number
    */
    queryTime: number;
};