/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FooCubeAggregationRow } from "./FooCubeAggregationRow.ts";

export type GetFooCubeAggregationsResponse = {
    /**
     * @type array
    */
    data: FooCubeAggregationRow[];
    /**
     * @type number
    */
    queryTime: number;
    /**
     * @type object
    */
    pagination: {
        /**
         * @type number
        */
        limit: number;
        /**
         * @type number
        */
        offset: number;
        /**
         * @type number
        */
        total: number;
    };
};