/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetFooFiltersValuesResponse = {
    /**
     * @type array
    */
    status: string[];
    /**
     * @type array
    */
    tags: string[];
    /**
     * @type array
    */
    priorities: number[];
};