/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetApiBarAverageValueQueryResponse } from "../types/GetApiBarAverageValue.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetApiBarAverageValueUrl() {
  const res = { method: 'GET', url: `/api/bar-average-value` as const }  
  return res
}

/**
 * @summary Egress endpoint for bar-average-value
 * {@link /api/bar-average-value}
 */
export async function getApiBarAverageValue(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiBarAverageValueQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetApiBarAverageValueUrl().url.toString(), ... requestConfig })  
  return res.data
}