/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetApiFooAverageScoreQueryResponse } from "../types/GetApiFooAverageScore.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetApiFooAverageScoreUrl() {
  const res = { method: 'GET', url: `/api/foo-average-score` as const }  
  return res
}

/**
 * @summary Egress endpoint for foo-average-score
 * {@link /api/foo-average-score}
 */
export async function getApiFooAverageScore(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiFooAverageScoreQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetApiFooAverageScoreUrl().url.toString(), ... requestConfig })  
  return res.data
}