/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetApiFooScoreOverTimeQueryResponse, GetApiFooScoreOverTimeQueryParams } from "../types/GetApiFooScoreOverTime.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetApiFooScoreOverTimeUrl() {
  const res = { method: 'GET', url: `/api/foo-score-over-time` as const }  
  return res
}

/**
 * @summary Egress endpoint for foo-score-over-time
 * {@link /api/foo-score-over-time}
 */
export async function getApiFooScoreOverTime(params?: GetApiFooScoreOverTimeQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiFooScoreOverTimeQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetApiFooScoreOverTimeUrl().url.toString(), params, ... requestConfig })  
  return res.data
}