/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetApiFooQueryResponse, GetApiFooQueryParams } from "../types/GetApiFoo.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetApiFooUrl() {
  const res = { method: 'GET', url: `/api/foo` as const }  
  return res
}

/**
 * @summary Egress endpoint for foo
 * {@link /api/foo}
 */
export async function getApiFoo(params?: GetApiFooQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiFooQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetApiFooUrl().url.toString(), params, ... requestConfig })  
  return res.data
}