/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetApiBarQueryResponse, GetApiBarQueryParams } from "../types/GetApiBar.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetApiBarUrl() {
  const res = { method: 'GET', url: `/api/bar` as const }  
  return res
}

/**
 * @summary Egress endpoint for bar
 * {@link /api/bar}
 */
export async function getApiBar(params?: GetApiBarQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiBarQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetApiBarUrl().url.toString(), params, ... requestConfig })  
  return res.data
}