/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetApiFooFiltersValuesQueryResponse, GetApiFooFiltersValuesQueryParams } from "../types/GetApiFooFiltersValues.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetApiFooFiltersValuesUrl() {
  const res = { method: 'GET', url: `/api/foo-filters-values` as const }  
  return res
}

/**
 * @summary Egress endpoint for foo-filters-values
 * {@link /api/foo-filters-values}
 */
export async function getApiFooFiltersValues(params?: GetApiFooFiltersValuesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiFooFiltersValuesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetApiFooFiltersValuesUrl().url.toString(), params, ... requestConfig })  
  return res.data
}