/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetApiFooCubeAggregationsQueryResponse, GetApiFooCubeAggregationsQueryParams } from "../types/GetApiFooCubeAggregations.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetApiFooCubeAggregationsUrl() {
  const res = { method: 'GET', url: `/api/foo-cube-aggregations` as const }  
  return res
}

/**
 * @summary Egress endpoint for foo-cube-aggregations
 * {@link /api/foo-cube-aggregations}
 */
export async function getApiFooCubeAggregations(params?: GetApiFooCubeAggregationsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetApiFooCubeAggregationsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetApiFooCubeAggregationsUrl().url.toString(), params, ... requestConfig })  
  return res.data
}